### PR TITLE
feat: support Debian CUDA detection

### PR DESCRIPTION
**Pull request by twrightsman**
Uses paths from [Debian](https://packages.debian.org/bullseye/amd64/libcuda1/filelist). Created to fix https://github.com/prefix-dev/pixi/issues/294. As noted in the issue, simply building from source without this patch results in CUDA correctly being detected, but using the GitHub releases Linux binary doesn't work.

### CODE REVIEW

**Comment by wolfv** [comment]
@twrightsman thanks! Looks good to me! I wonder if the `current` subdirectory is necessary?

Does this file also exist for you? 

`/usr/lib/x86_64-linux-gnu/libcuda.so.1`

I'll update the branch so that the tests pass (you'll have to pull)

**Comment by twrightsman** [comment]
Thanks for taking a look!

Yes I think you're correct here, `/usr/lib/x86_64-linux-gnu/libcuda.so` and `/usr/lib/x86_64-linux-gnu/libcuda.so.1` exist and are symlinks to places in `/etc/alternatives`. Looks like these would be the better paths since they would be correctly updated through the Debian [Alternatives](https://wiki.debian.org/DebianAlternatives) system.

I'll go ahead and pull down your updates and make those changes.

**Comment by twrightsman** [comment]
Pushed; let me know if I should do any rearranging or changing of commit messages to match the project's conventions.

**Comment by wolfv** [comment]
We can fix the message when squash-merging :) Awesome & thanks for your contribution!

**Comment by baszalmstra** [comment]
I dont quite understand how this fixes the issue. You said that the musl based pixi install doesnt detect cuda correctly but building from source (not building with musl I assume) does work. It sounds to me like this is more of a musl issue.

Did you try building pixi as a musl binary with these changes?

**Comment by wolfv** [comment]
Sorry, I do have more questions after looking a bit closer. 

Do you have this package installed? https://packages.debian.org/sid/libnvidia-ml1
And do you not have the `libnvidia-ml.so` file, at all? Because it seems like `libcuda` and `libnvidia-ml` would be quite different shared libraries.

**Comment by twrightsman** [comment]
@baszalmstra Do you happen to have instructions on how to build with musl? I am happy to test further. I believe Debian defaults to glibc. We can also move this discussion to the issue if you want.

**Pull request closed without merging**
