### PR TITLE
Test propagation (issue #266)

### PR DESCRIPTION
**Pull request by wolfv**
I added a test for the eager propagation issue. 

Not sure how to resolve this properly yet!

### CODE REVIEW

**Comment by baszalmstra** [comment]
Do you mind if I close this one @wolfv ?

**Comment by baszalmstra** [comment]
bump @wolfv

**Comment by wolfv** [comment]
Should we try to add this test to `resolvo` now? I think it's still a valid concern. 

Basically the problem is that the algorithm:

- first selects `libgfortran 5 BN 32`
- then selects `libgfortran5 12.3.0`, but the constraint does not work with the selected build number of `libgfortran`
- backtracks, and selects older `libgfortran 5 BN 0` and then 
- selects latest `libgfortran5 12.3.0`

While it (should?) have done:

- first select `libgfortran 5 BN 32`
- figure out that constraint on `libgfortran5 12.3.0` does not work
- instead select `libgfortran5 12.2.0` where constraint works

**Comment by wolfv** [comment]
Hmm, actually this might also be the "inverse" problem where the solver backtracks too early :D 


```
libgfortran = 5.0.0 32
    libgfortran5>= 11.3
libgfortran = 5.0.0 0
    libgfortran5>=11.3

libgfortran5 = 12.3.0
    -> libgfortran = 5.0.0 0
libgfortran5 = 12.2.0
    -> libgfortran = 5.0.0 32
```

We first select 

`libgfortran = 5.0.0 32`, then find out that the latest `libgfortran5 = 12.3.0` is not compatible, backtrack, select an older `libgfortran` (instead of trying an older `libgfortran5`).

**Comment by wolfv** [comment]
I think it's something I might like to come back to. But we can also close it and not delete the branch

**Comment by baszalmstra** [comment]
We will take a look at this later. Closing for now.

**Pull request closed without merging**
