### PR TITLE
Add "sorted" macro to JSON data types

### PR DESCRIPTION
**Pull request by travishathaway**
fixes: #125

### CODE REVIEW

**Comment by travishathaway** [comment]
Just FYI, I had to install the `insta` command to review changes made to the snapshots with:

```bash
cargo install cargo-insta
```

Might be nice to mention that somewhere in the documentation eventually.

**Comment by wolfv** [comment]
`insta` is pretty nice, right? You're right, mentioning that would be good

**Comment by baszalmstra** [comment]
Thanks for the PR @travishathaway ! Already looks good to me!

I agree about insta, maybe you can create another issue or PR for that?

**Review by wolfv — APPROVED** [review]
Looks good to me!

**Comment by wolfv** [comment]
@travishathaway I think we're happy to merge the PR but holding back since you haven't marked it as ready for review yet. Happy to merge whenever you're ready! :)

**Comment by travishathaway** [comment]
Ready to merge 😎

**Pull request merged**
