### PR TITLE
make archive type `serialize` and `deserialize`

### PR DESCRIPTION
**Pull request by wolfv**
This would be useful to serialize the rattler-build outputs.

### CODE REVIEW

**Comment by baszalmstra** [comment]
Maybe it helps to use: https://serde.rs/variant-attrs.html#rename_all ?

**Comment by wolfv** [comment]
@baszalmstra would you rather have them serialized as lowercase, or as `tar.bz2` / `conda`? I don't have a strong preference. 
I more or less need this in rattler-build, but we could also skip serializing this option in rattler-build.

**Comment by baszalmstra** [comment]
> @baszalmstra would you rather have them serialized as lowercase, or as `tar.bz2` / `conda`? I don't have a strong preference. I more or less need this in rattler-build, but we could also skip serializing this option in rattler-build.

I have no strong preference, but I think if you serialize this to yaml the most beautiful would be `snake_case` perhaps?

**Comment by baszalmstra** [comment]
This seems to already be integrated in #392

**Pull request closed without merging**
